# Generated by Django 3.2.6 on 2021-08-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='catalog_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='labels',
            field=models.ManyToManyField(null=True, to='albums.Label'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='albums.Genre'),
        ),
    ]
